image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update || true
          - apt-get -qq install git-ftp
          - git ftp push --user $SFTP_username --passwd $SFTP_password --verbose sftp://104.248.251.23/var/www/html --insecure