image: php:5.6.31

pipelines:
  default:
    - step:
        script:
          - apt-get -qq install git-ftp
          - git ftp init --user $SFTP_username --passwd $SFTP_password sftp://$FTP_HOST/var/www/html/